spring:
  application:
    name: ajouorder

  datasource:
    url: jdbc:mysql://ajoutondb.hunian.site:3307/ajouorder
    username: root
    password: R7#zF@kL!n2QwX9m
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true